FROM php:8.1-fpm

WORKDIR /var/www

RUN apt-get update && apt-get install -y \
      apt-utils \
      libxml2-dev \
      libpq-dev \
      libpng-dev \
      libzip-dev \
      zip unzip \
      git && \
      docker-php-ext-install pdo_mysql && \
      docker-php-ext-install mysqli && \
      docker-php-ext-install bcmath && \
      docker-php-ext-install gd && \
      docker-php-ext-install zip && \
      docker-php-ext-install soap && \
      apt-get clean && \
      rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

COPY php.ini /usr/local/etc/php/conf.d/php.ini

# Install composer
ENV COMPOSER_ALLOW_SUPERUSER=1
RUN curl -sS https://getcomposer.org/installer | php -- \
    --filename=composer \
    --install-dir=/usr/local/bin

# Install nodejs
RUN curl -fsSL https://deb.nodesource.com/setup_lts.x | bash - && apt-get install -yqq nodejs

# clean downloaded packages to keep image size small
RUN apt-get clean


# Erstelle den Speicherordner
RUN mkdir -p storage/framework/{cache,sessions,testing,views}
RUN mkdir -p storage/logs

# Setze die Berechtigungen für den Speicherordner
RUN chown -R www-data:www-data storage

# RUN composer install --optimize-autoloader --no-dev
